---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: ./spec/data_bags
  encrypted_data_bag_secret_key_path: ./spec/data_bags/encrypted_data_bag_secret
  require_chef_omnibus: 13.7.16

transport:
  username: root # For a Ubuntu Box
  ssh_key: <%= ENV['KITCHEN_SSH_KEY'] %>

verifier:
  name: inspec

platforms:
  - name: centos-7.4
    driver:
      provider: virtualbox

suites:
  - name: default
    sudo: false
    run_list:
      - recipe[example_mail::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
